/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewa_ps;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 */
public class Member extends javax.swing.JFrame {
private final DefaultTableModel tabel;
    public Statement stt;
    public Connection con;
    private TableColumn column;
    /**
     * Creates new form Member
     */
    public Member() {
        initComponents();
        String[] judul={"Id Member","Nama Member","Jenis member","Potongan","Biaya"};
        tabel = new DefaultTableModel(judul,0);
        tabmenu.setModel(tabel);
        tampilkan_data();
        disable_all();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        a_idmember = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        a_nm = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        a_jenisM = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        a_diskon = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabmenu = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        a_biayaP = new javax.swing.JTextField();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("DAFTAR MEMBER");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 11, 235, 50));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Id Member");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 100, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText(":");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 100, -1, -1));
        getContentPane().add(a_idmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 100, 132, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Nama Member");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 138, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText(":");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 138, -1, -1));
        getContentPane().add(a_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 138, 132, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText("Jenis Member");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 176, -1, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText(":");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 176, -1, -1));

        a_jenisM.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH JENIS MEMBER --", "SILVER", "PLATINUM", "GOLD" }));
        a_jenisM.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_jenisMMouseClicked(evt);
            }
        });
        a_jenisM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_jenisMActionPerformed(evt);
            }
        });
        getContentPane().add(a_jenisM, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 176, 132, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText("Diskon");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 214, -1, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText(":");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 214, -1, -1));
        getContentPane().add(a_diskon, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 214, 132, -1));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 100, 114, -1));

        tambah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 100, -1, -1));

        hapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 184, 114, -1));

        simpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 142, 113, -1));

        edit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        edit.setText("EDIT");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(487, 233, 114, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setText("BATAL");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 142, 114, -1));

        tabmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabmenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 294, 698, 110));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText("Biaya Pembuatan");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 252, -1, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText(":");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 252, -1, -1));
        getContentPane().add(a_biayaP, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 252, 132, -1));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg dalam new.jpg"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 820, 460));

        setSize(new java.awt.Dimension(827, 497));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void a_jenisMMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_jenisMMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_a_jenisMMouseClicked

    private void a_jenisMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_jenisMActionPerformed
        // TODO add your handling code here:
        String jenis= (String)(a_jenisM.getSelectedItem());
        if(jenis == "SILVER"){
            a_diskon.setText("30000");
            a_biayaP.setText("80000");

        }
        else if(jenis == "PLATINUM"){
            a_diskon.setText("40000");
            a_biayaP.setText("100000");

        }
        else if(jenis == "GOLD"){
            a_diskon.setText("60000");
            a_biayaP.setText("120000");

        }

    }//GEN-LAST:event_a_jenisMActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        penomoran_otomatis();
        tambah.setEnabled(false);
        edit.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(true);
        clear.setEnabled(true);
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        if(a_idmember.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus Data Pemeriksaan ?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/sewa_ps","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM member where kd_member='"+a_idmember.getText()+"'");
                    JOptionPane.showMessageDialog(this, "Data Dihapus !");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
                }

            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        //Simpan Data
        String kd_m = a_idmember.getText();
        String nm_m = a_nm.getText();
        String jenis_m = (String) a_jenisM.getSelectedItem();
        String potongan = a_diskon.getText();
        String biaya = a_biayaP.getText();
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sewa_ps", "root", "");
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
                String sql="insert into member values('"+kd_m+"','"+nm_m+"','"+jenis_m+"','"+potongan+"','"+biaya+"')";
                int executeUpdate = statement.executeUpdate(sql);
                statement.close();
                JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                a_idmember.setText("");
                a_nm.setText("");
                a_jenisM.setSelectedItem("");
                a_diskon.setText("");
                a_biayaP.setText("");
                koneksi.close();
            }
            catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
                //System.err.println("Exception: "+e.getMessage());
            }
            finally {
                tampilkan_data();
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String kd_m = a_idmember.getText();
        String nm_m = a_nm.getText();
        String jenis_m = (String) a_jenisM.getSelectedItem();
        String potongan = a_diskon.getText();
        String biaya = a_biayaP.getText();
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sewa_ps", "root", "");
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
            String sql="UPDATE member SET kd_member='"+kd_m+"',nama_member='"+nm_m+"',jenis_member='"+jenis_m+"',potongan='"+potongan+"',biaya='"+biaya+"' WHERE kd_member='"+kd_m+"'";
            statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }finally{
            tampilkan_data();
        }
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        disable_all();

                a_idmember.setText("");
                a_nm.setText("");
                a_jenisM.setSelectedItem("-- PILIH JENIS MEMBER --");
                a_diskon.setText("");
                a_biayaP.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void tabmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmenuMouseClicked
        // TODO add your handling code here:
        a_idmember.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 0).toString());
        a_nm.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 1).toString());
        a_jenisM.setSelectedItem(tabmenu.getValueAt(tabmenu.getSelectedRow(), 2).toString());
        a_diskon.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 3).toString());
        a_biayaP.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 4).toString());

        String temp_idm = tabmenu.getValueAt(tabmenu.getSelectedRow(), 0).toString();

        tambah.setEnabled(false);
        edit.setEnabled(true);
        hapus.setEnabled(true);
        simpan.setEnabled(false);
        clear.setEnabled(true);
    }//GEN-LAST:event_tabmenuMouseClicked

    private void disable_all() {
        tambah.setEnabled(true);
        edit.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        clear.setEnabled(false);
       }
    
    private void tampilkan_data() {
        try {
            int data = tabmenu.getRowCount();
            for(int i=0;i<data;i++){
            tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/sewa_ps","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM member ORDER BY kd_member");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
    
    
     private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/sewa_ps","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    
    private void penomoran_otomatis() {
        int kode_m=0;
        String temp_kode_m="";
        try {
            koneksi();
            String sql = "select kd_member from member order by kd_member desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_kode_m = res.getString(1);                
                String nomor_blkg = temp_kode_m.substring(2,4);
                kode_m=Integer.parseInt(nomor_blkg);
            }
                        
            kode_m++;
            String nilai=String.valueOf(kode_m);                      
            if(nilai.length()==1){
                a_idmember.setText("M00"+kode_m);
            }else
            if(nilai.length()==2){
                a_idmember.setText("M0"+kode_m);
            }else
            if(nilai.length()==3){
                a_idmember.setText("M"+kode_m);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Member.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Member().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JTextField a_biayaP;
    private javax.swing.JTextField a_diskon;
    private javax.swing.JTextField a_idmember;
    private javax.swing.JComboBox<String> a_jenisM;
    private javax.swing.JTextField a_nm;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabmenu;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
