/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sewa_ps;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 */
public class transaksi extends javax.swing.JFrame {
    private final DefaultTableModel tabel;
    public Statement stt;
    public Connection con;
    private TableColumn column;
    
    
    public int totrental_, potongan, total;
    /**
     * Creates new form transaksi
     */
    public transaksi() {
        initComponents();
        String[] judul={"Kode Transaksi","Kode Rental","Nama Pelanggan","Total Rental","Id Member","Diskon","Total","Bayar","Kembali","Keterangan"};
        tabel = new DefaultTableModel(judul,0);
        tabmenu.setModel(tabel);
        tampilkan_data();
        disable_all();
        tampil_koderental();
        aktif(true);
        a_totrental.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        a_kdtransaksi = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        a_idmember = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        a_potongan = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        a_total = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        a_bayar = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        a_kembali = new javax.swing.JTextField();
        exit = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        simpan = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabmenu = new javax.swing.JTable();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        a_totrental = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        a_ket = new javax.swing.JComboBox<>();
        cbrental = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        a_nm = new javax.swing.JTextField();
        member = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("PEMBAYARAN");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(304, 23, 207, 50));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 0));
        jLabel7.setText("Kode Rental");
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 0));
        jLabel10.setText(":");
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 0));
        jLabel8.setText("Kode Transaksi");
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 106, -1, -1));

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 0));
        jLabel11.setText(":");
        jLabel11.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 106, -1, -1));
        getContentPane().add(a_kdtransaksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 132, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 0));
        jLabel9.setText("Id Member");
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 0));
        jLabel12.setText(":");
        jLabel12.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        a_idmember.setText("NON MEMBER");
        a_idmember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_idmemberActionPerformed(evt);
            }
        });
        getContentPane().add(a_idmember, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 260, 132, -1));

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 0));
        jLabel13.setText("Potongan");
        jLabel13.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 0));
        jLabel14.setText(":");
        jLabel14.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        a_potongan.setText("0");
        a_potongan.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                a_potonganInputMethodTextChanged(evt);
            }
        });
        a_potongan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_potonganActionPerformed(evt);
            }
        });
        getContentPane().add(a_potongan, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 132, -1));

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 0));
        jLabel15.setText("Total");
        jLabel15.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, -1, -1));

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 0));
        jLabel16.setText(":");
        jLabel16.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, -1, -1));
        getContentPane().add(a_total, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 320, 132, -1));

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 0));
        jLabel17.setText("Bayar");
        jLabel17.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 0));
        jLabel18.setText(":");
        jLabel18.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        a_bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_bayarActionPerformed(evt);
            }
        });
        getContentPane().add(a_bayar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 132, -1));

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 0));
        jLabel19.setText("Kembali");
        jLabel19.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 0));
        jLabel20.setText(":");
        jLabel20.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 380, -1, -1));
        getContentPane().add(a_kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 380, 132, -1));

        exit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 278, 114, -1));

        tambah.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        tambah.setText("TAMBAH");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 91, -1, -1));

        hapus.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        hapus.setText("HAPUS");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 182, 114, -1));

        simpan.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        simpan.setText("SIMPAN");
        simpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanActionPerformed(evt);
            }
        });
        getContentPane().add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(552, 133, 113, -1));

        edit.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        edit.setText("UPDATE");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 231, 114, -1));

        clear.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        clear.setText("BATAL");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        getContentPane().add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(551, 327, 114, -1));

        tabmenu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabmenuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabmenu);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 447, 698, 112));

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 0));
        jLabel21.setText("Total Rental");
        jLabel21.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 0));
        jLabel22.setText(":");
        jLabel22.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, -1, -1));
        getContentPane().add(a_totrental, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 132, -1));

        jLabel23.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 0));
        jLabel23.setText(":");
        jLabel23.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 410, -1, -1));

        jLabel24.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 0));
        jLabel24.setText("Keterangan");
        jLabel24.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        a_ket.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "SELESAI", "BELUM KEMBALI" }));
        a_ket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                a_ketMouseClicked(evt);
            }
        });
        a_ket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                a_ketActionPerformed(evt);
            }
        });
        getContentPane().add(a_ket, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 132, -1));

        cbrental.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-- PILIH --" }));
        cbrental.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbrentalActionPerformed(evt);
            }
        });
        getContentPane().add(cbrental, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 130, -1));

        jLabel25.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 0));
        jLabel25.setText("Nama Pelanggan");
        jLabel25.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 0));
        jLabel26.setText(":");
        jLabel26.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 170, -1, -1));
        getContentPane().add(a_nm, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 132, -1));

        member.setText("MEMBER");
        member.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                memberActionPerformed(evt);
            }
        });
        getContentPane().add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, -1, -1));

        jButton1.setText("HITUNG");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 290, -1, -1));

        jButton2.setText("HITUNG");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 350, -1, -1));

        jButton3.setText("CARI");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 70, -1));

        Bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bg umum.jpg"))); // NOI18N
        getContentPane().add(Bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-240, 0, 1140, 600));

        setSize(new java.awt.Dimension(815, 625));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        // TODO add your handling code here:
        penomoran_otomatis();
        tambah.setEnabled(false);
        edit.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(true);
        clear.setEnabled(true);
        member.setEnabled(true);
        aktif(false);
        aktifmember(false);
    }//GEN-LAST:event_tambahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        // TODO add your handling code here:
        if(a_kdtransaksi.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Pilih Data Terlebih Dahulu !");
        }
        else{
            int reply = JOptionPane.showConfirmDialog(this,"Hapus Data Pemeriksaan ?","Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (reply == JOptionPane.YES_OPTION) {
                try {
                    java.sql.Connection koneksi = (java.sql.Connection) DriverManager.getConnection("jdbc:mysql://localhost/sewa_ps","root","");
                    koneksi.createStatement().executeUpdate("DELETE FROM transaksi where kd_transaksi='"+a_kdtransaksi.getText()+"'");
                    JOptionPane.showMessageDialog(this, "Data Dihapus !");
                    tampilkan_data();
                } catch (SQLException ex) {
                    JOptionPane.showMessageDialog(this, "Data Gagal Dihapus !");
                }

            }
        }
    }//GEN-LAST:event_hapusActionPerformed

    private void simpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanActionPerformed
        // TODO add your handling code here:
        //Simpan Data
        String kd_tr = a_kdtransaksi.getText();
        String kd_rental = (String) cbrental.getSelectedItem();
        String nm = a_nm.getText();
        String tot = a_totrental.getText();
        String id_member = a_idmember.getText();
        String diskon = a_potongan.getText();
        String total = a_total.getText();
        String bayar = a_bayar.getText();
        String kembali = a_kembali.getText();
        String ket = (String) a_ket.getSelectedItem();
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver").newInstance();
                com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sewa_ps", "root", "");
                com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
                String sql="insert into transaksi values('"+kd_tr+"','"+kd_rental+"','"+nm+"','"+tot+"','"+id_member+"','"+diskon+"','"+total+"','"+bayar+"','"+kembali+"','"+ket+"')";
                int executeUpdate = statement.executeUpdate(sql);
                statement.close();
                JOptionPane.showMessageDialog(null, "Data berhasil dimasukkan..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
                a_kdtransaksi.setText("");
                a_totrental.setText("");
                a_nm.setText("");
                a_potongan.setText("");
                a_total.setText("");
                a_bayar.setText("");
                a_kembali.setText("");
                a_idmember.setText("");
                koneksi.close();
            }
            catch (     ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
            {
                JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
                //System.err.println("Exception: "+e.getMessage());
            }
            finally {
                tampilkan_data();
            }
        }
    }//GEN-LAST:event_simpanActionPerformed

    private void aktif(boolean x) {
      
      a_kdtransaksi.setEditable(x);
      cbrental.setEditable(!x);
      a_totrental.setEditable(!x);
      a_idmember.setEditable(!x);
      a_potongan.setEditable(!x);
      a_total.setEditable(!x);
      a_bayar.setEditable(!x);
      a_kembali.setEditable(!x);
      a_ket.setEditable(true);
      
      
    }
    
    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        String kd_tr = a_kdtransaksi.getText();
        String kd_rental = (String) cbrental.getSelectedItem();
        String nm = a_nm.getText();
        String tot = a_totrental.getText();
        String id_member = a_idmember.getText();
        String diskon = a_potongan.getText();
        String total = a_total.getText();
        String bayar = a_bayar.getText();
        String kembali = a_kembali.getText();
        String ket = (String) a_ket.getSelectedItem();
        try {
            Class.forName("com.mysql.jdbc.Driver").newInstance();
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sewa_ps", "root", "");
            com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
            String sql="UPDATE transaksi SET kd_transaksi='"+kd_tr+"',kd_rental='"+kd_rental+"',nm_pelanggan='"+nm+"',total_rental='"+tot+"',id_member='"+id_member+"',potongan='"+diskon+"',total='"+total+"',bayar='"+bayar+"',kembali='"+kembali+"',keterangan='"+ket+"' WHERE kd_transaksi LIKE '"+kd_tr+"'";
            statement.executeUpdate(sql);
            statement.close();
            JOptionPane.showMessageDialog(null, "Data berhasil diedit..","Insert Data",JOptionPane.INFORMATION_MESSAGE);
            a_kdtransaksi.setText("");
                a_totrental.setText("");
                a_nm.setText("");
                a_potongan.setText("");
                a_total.setText("");
                a_bayar.setText("");
                a_kembali.setText("");
                a_idmember.setText("");
            koneksi.close();
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Eror: "+e,"Gagal",JOptionPane.WARNING_MESSAGE);
            //System.err.println("Exception: "+e.getMessage());
        }finally{
            tampilkan_data();
        }
    }//GEN-LAST:event_editActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        disable_all();

        a_kdtransaksi.setText("");
        a_potongan.setText("");
        a_nm.setText("");
        a_totrental.setText("");
        a_total.setText("");
        a_bayar.setText("");
        a_kembali.setText("");
        a_idmember.setText("NON MEMBER");
        a_ket.setSelectedItem("");
        cbrental.setSelectedItem("-- PILIH --");
    }//GEN-LAST:event_clearActionPerformed

    private void tabmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabmenuMouseClicked
         // TODO add your handling code here:
         a_kdtransaksi.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 0).toString());
        cbrental.setSelectedItem(tabmenu.getValueAt(tabmenu.getSelectedRow(), 1).toString());
        a_nm.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 2).toString());
        a_totrental.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 3).toString());
        a_idmember.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 4).toString());
        a_potongan.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 5).toString());
        a_total.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 6).toString());
        a_bayar.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 7).toString());
        a_kembali.setText(tabmenu.getValueAt(tabmenu.getSelectedRow(), 8).toString());
        a_ket.setSelectedItem(tabmenu.getValueAt(tabmenu.getSelectedRow(), 9).toString());
            
        String temp_kd_tr = tabmenu.getValueAt(tabmenu.getSelectedRow(), 0).toString();
        
        tambah.setEnabled(false);
        edit.setEnabled(true);
        hapus.setEnabled(true);
        simpan.setEnabled(false);
        clear.setEnabled(true);
        member.setEnabled(true);
        
    }//GEN-LAST:event_tabmenuMouseClicked

    private void a_idmemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_idmemberActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_a_idmemberActionPerformed

    private void a_potonganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_potonganActionPerformed
        // TODO add your handling code here:
          
    }//GEN-LAST:event_a_potonganActionPerformed

    private void a_bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_bayarActionPerformed
        // TODO add your handling code here:
            
        
    }//GEN-LAST:event_a_bayarActionPerformed

    private void a_ketMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_a_ketMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_a_ketMouseClicked

    private void a_ketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_a_ketActionPerformed
        // TODO add your handling code here:
                

    }//GEN-LAST:event_a_ketActionPerformed

    private void cbrentalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbrentalActionPerformed
        // TODO add your handling code here:
        String kode_rental = (String) cbrental.getSelectedItem();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sewa_ps", "root", "");
com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
String sql="SELECT * FROM rental WHERE kdrental like '"+kode_rental+"' ORDER BY kdrental ;";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{
a_nm.setText(rs.getString(2));
a_totrental.setText(rs.getString(6));

}
statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }//GEN-LAST:event_cbrentalActionPerformed

     private void aktifmember(boolean x) {
      
      a_idmember.setEditable(x);
      a_potongan.setEditable(x);
     }
    
    
    private void memberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_memberActionPerformed
        // TODO add your handling code here:
        if(member.isSelected()){
            aktifmember(true);
            a_idmember.setText("");
} else {
           
        }
    }//GEN-LAST:event_memberActionPerformed

    private void a_potonganInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_a_potonganInputMethodTextChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_a_potonganInputMethodTextChanged

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        totrental_ = Integer.parseInt(a_totrental.getText());
            potongan = Integer.parseInt(a_potongan.getText());
            total = totrental_ - potongan;

            a_total.setText(total + "");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        totrental_ = Integer.parseInt(a_total.getText());
            potongan = Integer.parseInt(a_bayar.getText());
            total = potongan - totrental_;
            a_kembali.setText(total + "");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String kode_member = a_idmember.getText();
try
{
Class.forName("com.mysql.jdbc.Driver").newInstance();
com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://127.0.0.1/sewa_ps", "root", "");
com.mysql.jdbc.Statement statement = (com.mysql.jdbc.Statement) koneksi.createStatement();
String sql="SELECT * FROM member WHERE kd_member like '"+kode_member+"' ORDER BY kd_member ;";
 ResultSet rs = statement.executeQuery(sql);
if (rs.next())
{

a_potongan.setText(rs.getString(4));

}
else
{
JOptionPane.showMessageDialog(null, "Data tidak ditemukan ","Insert Data",JOptionPane.INFORMATION_MESSAGE);
}
statement.close();
koneksi.close();
}
catch ( ClassNotFoundException | InstantiationException | IllegalAccessException | SQLException | HeadlessException e)
{
JOptionPane.showMessageDialog(null, "Eror:"+e,"Gagal",JOptionPane.WARNING_MESSAGE);
//System.err.println("Exception: "+e.getMessage());
}
    }//GEN-LAST:event_jButton3ActionPerformed

    
     private void disable_all() {
        tambah.setEnabled(true);
        edit.setEnabled(false);
        hapus.setEnabled(false);
        simpan.setEnabled(false);
        clear.setEnabled(true);
        member.setEnabled(false);
        }
    
    private void tampilkan_data() {
        try {
            int data = tabmenu.getRowCount();
            for(int i=0;i<data;i++){
            tabel.removeRow(0);
            }
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/sewa_ps","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM transaksi ORDER BY kd_transaksi");            
            while(re.next()){                
                String[] tabel_master={re.getString(1),re.getString(2),re.getString(3),re.getString(4),re.getString(5),re.getString(6),re.getString(7),re.getString(8),re.getString(9),re.getString(10)};
                tabel.addRow(tabel_master);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Terjadi Kesalahan Tampil Tabel");
        }
    }
    
    private void tampil_koderental() {
        try {
            com.mysql.jdbc.Connection koneksi = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/sewa_ps","root","");
            ResultSet re=koneksi.createStatement().executeQuery("SELECT * FROM rental ORDER BY kdrental ASC");
            while(re.next()){
                cbrental.addItem(re.getString("kdrental"));
                a_totrental.setText(re.getString("total"));
                
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Terjadi Kesalahan Tampil Kode Rental !");
        }
    }
    
     private void koneksi() {
        try {
            Class.forName("com.mysql.jdbc.Driver") ;
            con = (com.mysql.jdbc.Connection) DriverManager.getConnection("jdbc:mysql://localhost/sewa_ps","root","");
            stt = (Statement) con.createStatement();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Koneksi Database Error");
        }
    }
    
    private void penomoran_otomatis() {
        int kode_tr=0;
        String temp_kode_tr="";
        try {
            koneksi();
            String sql = "select kd_transaksi from transaksi order by kd_transaksi desc limit 1";                        
            ResultSet res=stt.executeQuery(sql);
            while (res.next()) {
                temp_kode_tr = res.getString(1);                
                String nomor_blkg = temp_kode_tr.substring(3,5);
                kode_tr=Integer.parseInt(nomor_blkg);
            }
                        
            kode_tr++;
            String nilai=String.valueOf(kode_tr);                      
            if(nilai.length()==1){
                a_kdtransaksi.setText("TR00"+kode_tr);
            }else
            if(nilai.length()==2){
                a_kdtransaksi.setText("TR0"+kode_tr);
            }else
            if(nilai.length()==3){
                a_kdtransaksi.setText("TR"+kode_tr);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Terjadi Error Penomoran !");
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bg;
    private javax.swing.JTextField a_bayar;
    private javax.swing.JTextField a_idmember;
    private javax.swing.JTextField a_kdtransaksi;
    private javax.swing.JTextField a_kembali;
    private javax.swing.JComboBox<String> a_ket;
    private javax.swing.JTextField a_nm;
    private javax.swing.JTextField a_potongan;
    private javax.swing.JTextField a_total;
    private javax.swing.JTextField a_totrental;
    private javax.swing.JComboBox<String> cbrental;
    private javax.swing.JButton clear;
    private javax.swing.JButton edit;
    private javax.swing.JButton exit;
    private javax.swing.JButton hapus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton member;
    private javax.swing.JButton simpan;
    private javax.swing.JTable tabmenu;
    private javax.swing.JButton tambah;
    // End of variables declaration//GEN-END:variables
}
